### PR TITLE
Added 'uploader: ObjectId' field to Image collection

### LINKED ISSUE #28: Image Schema update
We should add Uploader as a field in the collection.

### PR DESCRIPTION
**Pull request by DeveloperTK**
Resolves #28

### CODE REVIEW

**Review by yJulian — COMMENTED** [review]
Nice.
But could you look if thats the proper way to link with mongoose?
I dont know if we can link with User as a type instead of the id

**Comment by Voakie** [comment]
@yJulian using the ID is right, but we could also use references. The schema would then be:
```ts
uploader: { type: Types.ObjectId, ref: "User" },
```
The typings would be:
```ts
uploader: Types.ObjectId | IUserSchema;
```
And you would use it like this:
```ts
Image.find(...).populate("uploader").exec((err, res) => {
  const uploader = <IUserSchema>res.uploader;
  // typeof uploader: IUserSchema
});
```
we could also rename the interfaces from `IUserSchema` to `IUser` for better readability

**Comment by yJulian** [comment]
I knew that the ObjectID was right. But i think it could make it easier to develop it with a reference.
I think with a reference it could be easier to understand for newcommers and isn't that the advantage from mongoose over the official mongodb driver for node?

**Comment by Voakie** [comment]
If everyone agrees on this I could change the models to have references instead of the plain ID

**Comment by DeveloperTK** [comment]
Can someone else please implement this I'm not the best with mongoose

**Pull request merged**
